version: "3"
services:
  api-database:
    image: mongo:3.6
    restart: always
    container_name: "api-database"
    ports:
      - 27017:27017
    command: --smallfiles
  api:
    image: spring-mongo:1.0
    ports:
      - 9080:8080
    links:
      - api-database